import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { Exec } from '../exec.js';
import type { Log } from '../log.js';
import { exactTitlePattern, workspacePattern } from './match.js';
import type { WindowRaiser } from './types.js';

const KWIN = 'org.kde.KWin';
const SCRIPTING_PATH = '/Scripting';
const SCRIPTING_IFACE = 'org.kde.kwin.Scripting';
const SCRIPT_IFACE = 'org.kde.kwin.Script';
export const KWIN_PLUGIN_NAME = 'vscode-tmux-raise';

export interface KWinRaiserOptions {
  exec: Exec;
  /** Where the generated script is written; KWin reads it by path, so it must be an absolute path readable by the user's session. */
  scriptPath: string;
  pluginName?: string;
  writeScript?: (path: string, content: string) => void;
  log?: Log;
  sleep?: (ms: number) => Promise<void>;
  /** Script runs per raise: VS Code renames the window a moment after the editor opens. */
  attempts?: number;
  /** Focus polls after each run, `verifyIntervalMs` apart. */
  verifyAttempts?: number;
  verifyIntervalMs?: number;
}

/** True when KWin owns its name on the session bus (Plasma session, Wayland or X11). */
export async function kwinAvailable(exec: Exec): Promise<boolean> {
  return (await exec('busctl', ['--user', 'status', KWIN])).code === 0;
}

/**
 * KWin script that activates the VS Code window: the exact predicted title wins; otherwise the
 * single window whose title names the workspace. Runs inside KWin, so it sees native Wayland and
 * XWayland windows alike and is not subject to focus-stealing prevention. It has no return
 * channel; the caller verifies through the extension.
 */
export function kwinRaiseScript(title: string, workspaceName: string): string {
  return `// generated by vscode-tmux for one open request; loaded and unloaded through org.kde.kwin.Scripting
(function () {
  var exact = new RegExp(${JSON.stringify(exactTitlePattern(title))});
  var loose = new RegExp(${JSON.stringify(workspacePattern(workspaceName))});
  var windows = typeof workspace.windowList === 'function' ? workspace.windowList() : workspace.stackingOrder;
  var hit = null;
  var candidates = [];
  for (var i = 0; i < windows.length; i++) {
    var w = windows[i];
    if (!w.normalWindow) continue;
    if (exact.test(w.caption)) { hit = w; break; }
    if (loose.test(w.caption)) candidates.push(w);
  }
  if (hit === null && candidates.length === 1) hit = candidates[0];
  if (hit !== null) workspace.activeWindow = hit;
})();
`;
}

/**
 * Raises windows through KWin's scripting D-Bus interface with `busctl` (part of systemd), so
 * Plasma needs no extra tool. Per attempt: write the script, load it under a fixed plugin name,
 * run it, poll the extension for focus, unload it. Raises are serialized because they share the
 * script file and the plugin name.
 */
export class KWinRaiser implements WindowRaiser {
  private readonly log: Log;
  private readonly sleep: (ms: number) => Promise<void>;
  private readonly pluginName: string;
  private readonly writeScript: (path: string, content: string) => void;
  private readonly attempts: number;
  private readonly verifyAttempts: number;
  private readonly verifyIntervalMs: number;
  private queue: Promise<unknown> = Promise.resolve();

  constructor(private readonly o: KWinRaiserOptions) {
    this.log = o.log ?? (() => {});
    this.sleep = o.sleep ?? ((ms) => new Promise((r) => setTimeout(r, ms)));
    this.pluginName = o.pluginName ?? KWIN_PLUGIN_NAME;
    this.writeScript =
      o.writeScript ??
      ((path, content) => {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, content);
      });
    this.attempts = o.attempts ?? 3;
    this.verifyAttempts = o.verifyAttempts ?? 5;
    this.verifyIntervalMs = o.verifyIntervalMs ?? 100;
  }

  raise(title: string, workspaceName: string, isFocused: () => Promise<boolean>): Promise<boolean> {
    const run = this.queue.then(() => this.doRaise(title, workspaceName, isFocused));
    this.queue = run.catch(() => undefined);
    return run;
  }

  private async doRaise(title: string, workspaceName: string, isFocused: () => Promise<boolean>): Promise<boolean> {
    const script = kwinRaiseScript(title, workspaceName);
    for (let attempt = 0; attempt < this.attempts; attempt++) {
      if (!(await this.runScript(script))) return false;
      try {
        for (let poll = 0; poll < this.verifyAttempts; poll++) {
          await this.sleep(this.verifyIntervalMs);
          if (await isFocused()) return true;
        }
      } finally {
        await this.unload();
      }
    }
    this.log(`KWin: window titled ${JSON.stringify(title)} did not take focus`);
    return false;
  }

  /** Write, load and start the script. False (logged) when any D-Bus step fails. */
  private async runScript(script: string): Promise<boolean> {
    try {
      this.writeScript(this.o.scriptPath, script);
    } catch (err) {
      this.log(`KWin: cannot write ${this.o.scriptPath}: ${(err as Error).message}`);
      return false;
    }
    await this.unload(); // a leftover from an interrupted run would make loadScript return -1
    const loaded = await this.busctl(['--json=short', 'call', KWIN, SCRIPTING_PATH, SCRIPTING_IFACE, 'loadScript', 'ss', this.o.scriptPath, this.pluginName]);
    const id = loaded.code === 0 ? parseLoadedId(loaded.stdout) : undefined;
    if (id === undefined || id < 0) {
      this.log(`KWin: loadScript failed (${loaded.code}): ${loaded.stderr.trim() || loaded.stdout.trim() || 'no script id'}`);
      return false;
    }
    const run = await this.busctl(['call', KWIN, `${SCRIPTING_PATH}/Script${id}`, SCRIPT_IFACE, 'run']);
    if (run.code !== 0) {
      this.log(`KWin: Script${id}.run failed (${run.code}): ${run.stderr.trim()}`);
      await this.unload();
      return false;
    }
    return true;
  }

  private async unload(): Promise<void> {
    await this.busctl(['call', KWIN, SCRIPTING_PATH, SCRIPTING_IFACE, 'unloadScript', 's', this.pluginName]);
  }

  private busctl(args: string[]) {
    return this.o.exec('busctl', ['--user', ...args]);
  }
}

/** `busctl --json=short call ... loadScript` prints `{"type":"i","data":[<id>]}`. */
export function parseLoadedId(stdout: string): number | undefined {
  try {
    const parsed = JSON.parse(stdout) as { data?: unknown[] };
    const id = parsed.data?.[0];
    return typeof id === 'number' ? id : undefined;
  } catch {
    return undefined;
  }
}
